name: API Health Check

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  # Also allow manual triggering
  workflow_dispatch:
  # Run on push to the repository
  push:
    branches:
      - main
      - master
  # Run on pull requests
  pull_request:
    branches:
      - main
      - master

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Check API health
        id: health-check
        uses: jtalk/url-health-check-action@v3
        with:
          url: ${{ secrets.API_HEALTH_URL }}
          max-attempts: 3
          retry-delay: 5s
          follow-redirect: true
          
      - name: Notify on failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: alerts
          SLACK_COLOR: danger
          SLACK_TITLE: API Health Check Failed
          SLACK_MESSAGE: 'The health check for username-api has failed. Please check the service health endpoint.'
          SLACK_FOOTER: "Powered by GitHub Actions"
          
      - name: Record status
        run: |
          echo "Health check at $(date -u) - Status: ${{ steps.health-check.outcome }}" >> $GITHUB_STEP_SUMMARY
          echo "URL checked: API health endpoint" >> $GITHUB_STEP_SUMMARY